### ISSUE TITLE
invalid `openarray` syntax highlighting

### ISSUE THREAD

**Issue by arnetheduck** [saem/vscode-nim#27]
It's actually spelled [`openArray`](https://github.com/nim-lang/Nim/blob/b68ecc82cb404dbbd291320139955794e88c24ff/lib/system.nim#L305)

**Comment by saem** [comment]
d'oh!

**Comment by saem** [comment]
hmm, so due to case insensitivity it could be either, so I suppose I should allow both.

**Comment by arnetheduck** [comment]
> hmm, so due to case insensitivity it could be either, so I suppose I should allow both.

well, the canonical spelling is `openArray` per the declaration (and per the style check option) - if you want full support for all kinds of spellings, there's an infinite number of them like `o_Pe_naRr_ay` etc

**Comment by arnetheduck** [comment]
one reason we're highlighting this is that there's an expectation, specially when conducting security reviews, that all code uses the same spelling in general (also because this is supported better by tooling in general) - ideally, the first thing to support would be the correct spelling - highlighting alternative spellings can be seen as a separate enhancement at that point

**Comment by saem** [comment]
Fixed in https://github.com/saem/vscode-nim/commit/1573c7268d2824480c2f6356a7c9829ed14a5419
