### ISSUE TITLE
Autocomplete of enums values

### ISSUE THREAD

**Issue by gavr123456789** [saem/vscode-nim#35]
![image](https://user-images.githubusercontent.com/30507409/111439217-339eaf80-8716-11eb-847c-17b1fa958956.png)
Maybe this is an autosuggest problem, I just started learning nim and don't know where its repository is located.

**Comment by RSDuck** [comment]
that's an nimsuggest issue

**Comment by ghost** [comment]
This was fixed on devel, probably via https://github.com/nim-lang/Nim/pull/16676, and it's not a vscode-nim issue
