### ISSUE TITLE
`.nims` files get incorrent errors

### ISSUE THREAD

**Issue by dawkot** [saem/vscode-nim#41]
It would be better not to check `.nims` files at all if it can't be immediately fixed.

# Example
Editor will complain that procedure `setCommand` doesn't exist in a `.nims` file if we try to call it, even though it obviously does.

**Comment by binhonglee** [comment]
Porting [this issue](https://github.com/pragmagic/vscode-nim/issues/184) over as well since it is also nimscript related.

**Comment by saem** [comment]
Sorry, I can't replicate this issue.

**Comment by binhonglee** [comment]
Hey @saem, I have a repro step.

1. Clone https://github.com/binhonglee/wings
2. Open up src/main/scripts/preCompile.nims
3. Hit save

Unintended effect:
1. Underlines `mode` as an undeclared identifier
2. See a `const.nim` file created at the top level of the project directory.

**Comment by saem** [comment]
@binhonglee thanks for the reproduction, that's not the same error or maybe it is, in which case it's it's not really a problem.

In this case there is one thing to do, create a `nim.project` setting in `.vscode/setting.json` with an array of Nim file(s) that you actually compile. I think Nim check won't kick off for it anymore.

If that doesn't work the other issue, which is a nim issue, is that Nim check needs a Nim cfg file in the top level directory with the path specified as `.` or it won't know about the `const.nim` file.
