### ISSUE TITLE
Tens of nimsuggest processes

### ISSUE THREAD

**Issue by al6x** [saem/vscode-nim#42]
<img width="730" alt="Screen Shot 2021-06-02 at 1 45 39 pm" src="https://user-images.githubusercontent.com/94196/120467679-168a8c00-c3a9-11eb-871c-6f995ac9d8c8.png">

```
Nim VSCode v0.1.21
```

```
nim -v
Nim Compiler Version 1.4.6 [MacOSX: amd64]
Compiled at 2021-05-06
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

```
VSCode
Version: 1.56.2
```

**Comment by gavr123456789** [comment]
This is copy of https://github.com/saem/vscode-nim/issues/26

**Comment by saem** [comment]
Fixed.
