### ISSUE TITLE
Distinguish type definition from usage

### ISSUE THREAD

**Issue by al6x** [saem/vscode-nim#49]
Hi, would be nice to be able to distinguish type declaration from the type usage. For example to highlight it differently, make type definition bold. Currently it's impossible.

<img width="879" alt="Screen Shot 2021-08-14 at 6 39 18 am" src="https://user-images.githubusercontent.com/94196/129433162-c86ddeda-45f4-490b-8410-f279e7d9cda2.png">

P.S.

Additionally, would be nice to distinguish top-level function declaration vs function declaration inside of a function. Again to be able to highlight top level function declarations with bold.

**Comment by al6x** [comment]
I added additional highlight rules, to provide better highlighting for types. Note bold type declaration and grey type usage.

<img width="600" alt="Screen Shot 2021-08-16 at 8 48 06 am" src="https://user-images.githubusercontent.com/94196/129517589-eda5836f-be6d-48d2-a405-3090169fb836.png">

I'm using [additional plugin](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight). But it would be nice to integrate these rules into this `vscode-nim` extension.

The additional highlight rules I'm using (the full [rules config](https://gist.github.com/al6x/908eb77e002d3e1f56ea00983b0e4d11)).

```JavaScript
{
  "highlight.regexes": {
    // type Type
    "(\n)(type|with)(\\s+)([A-Z][a-zA-Z0-9]+)": {
      "filterFileRegex": ".*.nim$",
      "decorations": [
        {}, { "color": "#3730A3" }, {}, { "color": "#111827", "fontWeight": "bold" } // #3730A3
      ]
    },
    // Avoiding hiding `v: Time.now`
    "(: *)([A-Z][A-Za-z0-9_\\[\\]]*|int[^A-Za-z0-9]|string[^A-Za-z0-9]|float[^A-Za-z0-9]|void[^A-Za-z0-9]|bool[^A-Za-z0-9])\\.": {
      "filterFileRegex": ".*.nim$",
      "regexFlags": "g",
      "decorations": [
        {}, { "color": "#111827" }
      ]
    },
    // Custom types ignored
    "(: *)([A-Z][A-Za-z0-9_\\[\\]]*)": {
      "filterFileRegex": ".*.nim$",
      "regexFlags": "g",
      "decorations": [
        {}, { "color": "#9CA3AF" }
      ]
    },
    "(: *)(var|ref)( *[A-Z][A-Za-z0-9_\\[\\]]*)": {
      "filterFileRegex": ".*.nim$",
      "regexFlags": "g",
      "decorations": [
        {}, { "color": "#9CA3AF" }, { "color": "#9CA3AF" }
      ]
    },
    // Base types ignored
    "(: *)(int|string|float|void|bool)([^A-Za-z0-9])": {
      "filterFileRegex": ".*.nim$",
      "regexFlags": "g",
      "decorations": [
        {}, { "color": "#9CA3AF" }
      ]
    },
    "(: *)(var|ref)( *int|string|float|void|bool)([^A-Za-z0-9])": {
      "filterFileRegex": ".*.nim$",
      "regexFlags": "g",
      "decorations": [
        {}, { "color": "#9CA3AF" }, { "color": "#9CA3AF" }
      ]
    },
    // tuple, seq, range, Table
    "(: *)(tuple|seq|range|Table|type)(\\[[^\\]]+[\\]]+)": {
      "filterFileRegex": ".*.nim$",
      "regexFlags": "g",
      "decorations": [
        {}, { "color": "#9CA3AF" }, { "color": "#9CA3AF" }
      ]
    },
    "(: *)(ref *| var *)(tuple|seq|range|Table)(\\[[^\\]]+[\\]]+)": {
      "filterFileRegex": ".*.nim$",
      "regexFlags": "g",
      "decorations": [
        {}, { "color": "#9CA3AF" }, { "color": "#9CA3AF" }, { "color": "#9CA3AF" }
      ]
    }
  }
}
```

**Comment by canelhasmateus** [comment]
Syntax highlighting is an area that i believe could be improved upon. How should we go about it, @saem ?

**Comment by saem** [comment]
I'm not convinced by this issue.

For syntax highlighting there are in depth documentation on the vscode site. I would start with some principles for how to approach classification for highlighting and then submit PRs.
