### ISSUE TITLE
code formatting

### ISSUE THREAD

**Issue by RSDuck** [saem/vscode-nim#5]
it looks like some files use four space indentation while others use two space indentation. Also some things are unusual like putting type names without a space behind a colon.

**Comment by saem** [comment]
Totally OK hammering it with a formatting tool, only thing I feel strongly about is narrow width lines (80 characters). Reasoning being it lets me put up many split views side by side as I have a wide screen and it's like to have a bunch of code up as reference.

Backstory being, I didn't really learn Nim style, after a while porting I started to get more conservative about line width, so I started trimming back spaces after colons. The mixed indentation is not something I felt strongly about at the time one way or the other, the mixed TypeScript code base was nudging the editor to use 4 space formatting. Then grabbing Nim code from various sources I picked up some two space indentation.

**Comment by auxym** [comment]
This is slightly off-topic, but perhaps this extension could add `nimpretty` integration as an additional feature?

**Comment by RSDuck** [comment]
I think it's already in there

**Comment by saem** [comment]
After #15 is closed and #16 is merged, I'll bash the code with nimpretty.

After than gradual changes to use `let`, `var`, `type`, etc... in block format, using result, etc... can happen per PR.

**Comment by saem** [comment]
Fixed as part of #17
