### ISSUE TITLE
"useNimsuggestCheck" setting isn't specified in package.json

### ISSUE THREAD

**Issue by RSDuck** [saem/vscode-nim#6]
This seems to be carried from the original codebase, though the default value was changed from false to true which is why I noticed it.

**Comment by saem** [comment]
For the default, I still haven't figured out the subtleties of Nim tooling. So if one way or the other is "better" or much closer to what suits the intention of how it should be used I'd be happy to have you tell me my opinion in the interim. ;)

**Comment by RSDuck** [comment]
using nimsuggest for checking seems to be a lot faster, but it doesn't check errors in the entire project only in the current file, while nim check.

Also it looks like nim check is broken with this extension 🙁. Another thing I noticed are that probably nim check uses 1 based columns while nimsuggest uses zero based (so my [change](https://github.com/saem/vscode-nim/blob/master/src/nimvscode/vscodeExt.nim#L66) made it work the other way around).

**Comment by saem** [comment]
That explains the off by one highlight error prior too. I'll look at Nim check today. I'm inclined to perhaps remove nimsuggest check entirely for now.

The design issues and lack of tests feel really apparent, and now that the mechanical port is "done", the focus should be on fundamentals prior to trying to bolt on new functionality or sustaining extra features.

**Comment by saem** [comment]
> Also it looks like nim check is broken with this extension.

I got it working on my machine, the [backend parameter was being passed after the file name which is out of position](https://github.com/saem/vscode-nim/blob/master/src/nimvscode/nimBuild.nim#L211).

> Another thing I noticed are that probably nim check uses 1 based columns while nimsuggest uses zero based (so my [change](https://github.com/saem/vscode-nim/blob/master/src/nimvscode/vscodeExt.nim#L66) made it work the other way around).

Late night/phone code reviews, I didn't notice the column offset changes. I think that making it all uniform should be done by the nim check and nimsuggest check code respectively, so I'll see about moving that there.

**Comment by saem** [comment]
Fix is up in the master branch, I'll release soon.

**Comment by saem** [comment]
Fix should be out with the latest extension release.
