### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by dscottboggs** [saem/vscode-nim#8]
This extension no longer shows up in the extensions search for users who use open-source builds of VSCode, or "VSCodium", at least on Arch Linux and its derivatives, because these builds have switched to the "Open VSX" extension repository. Instructions for publishing can be found [in the OpenVSX wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Similar issues have also been posted to the pragmagic/vscode-nim repository: [#176](https://github.com/pragmagic/vscode-nim/issues/176) and [#178](https://github.com/pragmagic/vscode-nim/issues/178). However, that version of the repository seems to be abandoned.

I suspect the reason this was not picked up by the initial migration is because it lists `ms-vscode.cpptools` as a dependency, however, browsing the repository, it's not immediately clear why that extension is a dependency.

**Comment by RSDuck** [comment]
> I suspect the reason this was not picked up by the initial migration is because it lists ms-vscode.cpptools as a dependency, however, browsing the repository, it's not immediately clear why that extension is a dependency.

I think it is for debugging support

**Comment by dscottboggs** [comment]
> debugging support

Oh dear. This is going to break a lot of the extensions I rely on :weary:

**Comment by RSDuck** [comment]
the debugging "support" is not really substantial. It's basically [two lines](https://github.com/pragmagic/vscode-nim/commit/823f135a37d147a0c17f327e7bf3f3ea6df57f0c), one adding the dependency and the other is for allowing breakpoints in Nim source files.

The official C++ extension is also not the only gdb debugger implementation for VSC, there's e.g. also: https://marketplace.visualstudio.com/items?itemName=webfreak.debug

**Comment by dscottboggs** [comment]
oh sweet. I will work up a PR to remove that dependency then. I feel confident @saem will respond to this, but if he doesn't after a while, or feels that this change is not desired, someone can ping me and I'll publish from my fork.

In the meantime, I have installed the extension successfully through sideload by:

- ~~removing the dependency from `package.json`~~ clone my fork of the repo and checkout the branch with the fixes:
```sh
git clone git@github.com:dscottboggs/vscode-nim.git
git checkout fix/prepare-for-openvsx
```
- building the extension package with
```sh
npm install
./node_modules/vsce/out/vsce package
```
- Installing the built package by opening VSCode, navigating to the Extensions left-bar-tab (Ctrl+Shift+X), then clicking the drop-down -> Install from VSIX... then choosing the archive.

**Comment by saem** [comment]
I'm very much for having the extension being usable for VSCodium and friends. So thanks for raising the issue and creating the PR (#10). I have a bit of feedback so I'll comment there.

**Comment by saem** [comment]
Thanks for #10 @dscottboggs. I'll release ASAP, work is a bit bonkers presently.

**Comment by saem** [comment]
0.1.8 released.

@dscottboggs at this point is actually publishing to Open VSX the only remaining task? I'm presuming that's mostly me setting up some credentials and publishing there as well per the linked instructions?

**Comment by dscottboggs** [comment]
yes, that should be it, thanks for all your work on this!

**Comment by saem** [comment]
Published here: https://open-vsx.org/extension/nimsaem/nimvscode

Claiming namespace here: https://github.com/eclipse/open-vsx.org/issues/189

@dscottboggs if everything is working on your end, can we consider this closed?

**Comment by dscottboggs** [comment]
For sure ---- On Sat, 24 Oct 2020 16:02:52 -0400  notifications@github.com  wrote ----
Published here: https://open-vsx.org/extension/nimsaem/nimvscode
Claiming namespace here: eclipse/open-vsx.org#189
@dscottboggs if everything is working on your end, can we consider this closed?
