### ISSUE TITLE
undeclared identifier: newContext() with std/net

### ISSUE THREAD

**Issue by RokkuCode** [saem/vscode-nim#80]
With the following snippet from the official error i got an error but it compiles fine:

````
import std/net

let socket = newSocket()
let ctx = newContext()
wrapSocket(ctx, socket)
socket.connect("google.com", Port(443))
````
Result:
![Screenshot_20220314_035201](https://user-images.githubusercontent.com/3813927/158096778-b6e37e18-bc1b-41a1-a91a-0cf849475b2d.png)

With hovering the newContext() I got:
![Screenshot_20220314_035132](https://user-images.githubusercontent.com/3813927/158096787-cf5bc931-a329-4ae7-b0c8-3d7c54a44c3a.png)

**Comment by RSDuck** [comment]
see https://github.com/pragmagic/vscode-nim/issues/70

**Comment by RSDuck** [comment]
see https://github.com/pragmagic/vscode-nim/issues/70
except that you need to supply the flag -d:ssl instead of --threads:on
