### ISSUE TITLE
Hint is in problems tab

### ISSUE THREAD

**Issue by heinthanth** [saem/vscode-nim#99]
I'm not sure. But I think "Hint" should not be in Problems tab or marked as Warning.

<img alt="Screen Shot 2022-07-06 at 11 42 47 AM" src="https://user-images.githubusercontent.com/43804263/177473549-0164d69d-a34a-4ccc-94b5-7cacc4ab72b8.png">

I added that hint to hint to me about version number. And it's not warning. Is there anything we can do about it?

**Comment by quantimnot** [comment]
A hint is a diagnostic message like a warning and error. The "problems" tab is for diagnostics.

There is no bug here. Click the funnel icon in the filter control in the problems tab and uncheck "Show Infos".
